---
# site-pkg.yml

- import_playbook: site-check.yml

- name: pkg
  hosts: all

  vars:
    pkg_delete_unused: false
    pkg_force: ""
    pkg_packages: "*"
    pkg_replace_existing: false
    pkg_state: "latest"
    pkg_title: "update"

  tasks:
    - name: "{{ pkg_title }} package(s)"
      pkg:
        delete_unused: "{{ pkg_delete_unused if pkg_delete_unused else omit }}"
        force: "{{ pkg_force if pkg_force else omit }}"
        name: "{{ pkg_packages }}"
        replace_existing: >-
          {{ pkg_replace_existing if pkg_replace_existing else omit }}
        state: "{{ pkg_state }}"
      register: pkg_result

    - name: show results if there were changes
      debug:
        msg: "{{ pkg_result.stdout_lines }}"
      when: pkg_result.changed
