- name: Package
  hosts: all
  vars:
    pkg_packages: "*"
    pkg_state: "latest"

  tasks:
    - name: update packages
      pkg:
        name: "{{ pkg_packages }}"
        state: "{{ pkg_state }}"
