# site-web.yml

- name: Web
  any_errors_fatal: true
  gather_facts: false
  hosts: web

  pre_tasks:
    - name: collect facts if missing
      setup:
      when: >-
        ansible_facts is undefined
        or not ansible_facts

  roles:
    - role: openbsd.httpd
      tags: [httpd]
