---
# site.yml

- import_playbook: site-check.yml
  tags: [always, check]

- import_playbook: site-update.yml
  tags: [never, update]

- import_playbook: site-core.yml
  tags: [core]

- import_playbook: site-firewall.yml
  tags: [never, firewall]

- import_playbook: site-dns.yml
  tags: [never, dns]

- import_playbook: site-mail.yml
  tags: [never, mail]

- import_playbook: site-web.yml
  tags: [never, web]

- import_playbook: site-acme.yml
  tags: [never, acme]
