---
# site-update.yml

- name: Update
  any_errors_fatal: true
  gather_facts: false
  hosts: all

  pre_tasks:
    - name: collect facts if missing
      setup:
      when: >-
        ansible_facts is undefined
        or not ansible_facts

  roles:
    - role: openbsd.syspatch
      tags: [syspatch]

    - role: openbsd.sysupgrade
      tags: [sysupgrade]
