# site-core.yml

- name: Core
  any_errors_fatal: true
  gather_facts: false
  hosts: all

  pre_tasks:
    - name: collect facts if missing
      setup:
      when: >-
        ansible_facts is undefined
        or not ansible_facts

  roles:
    - role: openbsd.doas
      tags: [doas]

    - role: openbsd.ntpd
      tags: [ntpd]

    - role: openbsd.pf
      tags: [pf]
