---
# site-pkg.yml

- import_playbook: site-check.yml

- name: pkg
  hosts: all

  vars:
    pkg_force: ""
    pkg_packages: "*"
    pkg_state: "latest"
    pkg_title: "update"

  tasks:
    - name: "{{ pkg_title }} package(s)"
      pkg:
        force: "{{ pkg_force if pkg_force else omit }}"
        name: "{{ pkg_packages }}"
        state: "{{ pkg_state }}"
      register: pkg_result

    - name: show results if there were changes
      debug:
        msg: "{{ pkg_result.stdout_lines }}"
      when: pkg_result.changed
