---
# site-sysupgrade.yml

- import_playbook: site-check.yml

- name: sysupgrade
  hosts: all

  vars:
    sysupgrade_branch: "auto"
    sysupgrade_force: false
    sysupgrade_reboot: true
    sysupgrade_reboot_timeout: "600"
    sysupgrade_title: "release or snapshot"

  tasks:
    - name: "upgrade to latest {{ sysupgrade_title }}"
      sysupgrade:
        branch: "{{ sysupgrade_branch }}"
        force: "{{ sysupgrade_force }}"
      register: sysupgrade_result
      when: ansible_distribution_version is version("6.6", ">=")

    - name: reboot if upgraded
      ansible.builtin.reboot:
        connect_timeout: "{{ sysupgrade_reboot_timeout }}"
        reboot_timeout: "{{ sysupgrade_reboot_timeout }}"
      when:
        - sysupgrade_result.changed
        - sysupgrade_result.reboot
        - sysupgrade_reboot
