---
# site-acme.yml

- name: Acme
  any_errors_fatal: true
  gather_facts: false
  hosts: acme
  tags: [never, acme]

  pre_tasks:
    - name: collect facts if missing
      setup:
      when: >-
        ansible_facts is undefined
        or not ansible_facts

  roles:
    - role: openbsd.acme
      tags: [acme]
