---
# site-pkg.yml

- import_playbook: site-check.yml

- name: pkg
  hosts: all

  vars:
    pkg_delete_unused: false
    pkg_force: ""
    pkg_packages: "*"
    pkg_replace_existing: false
    pkg_state: "latest"
    pkg_title: "install or update"

  tasks:
    - name: "{{ pkg_title }} package(s)"
      pkg:
        delete_unused: "{{ pkg_delete_unused }}"
        force: "{{ pkg_force if pkg_force else omit }}"
        name: "{{ pkg_packages }}"
        replace_existing: "{{ pkg_replace_existing }}"
        state: "{{ pkg_state }}"
