---
# tasks file for openbsd.sysupgrade

- name: upgrade to latest release or snapshot
  sysupgrade:
    branch: "{{ sysupgrade_branch }}"
  register: upgraded
  when: ansible_distribution_version >= "6.6"

- name: reboot if upgraded
  reboot:
    connect_timeout: 600
    reboot_timeout: 600
  when:
    - upgraded.changed
    - sysupgrade_reboot

- name: reinstall snapshot packages if rebooted and running *-current
  command: pkg_add -ruD snap
  when:
    - ansible_distribution_release == "current"
    - upgraded.changed
