# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Configure dhclient.conf
  ansible.builtin.template:
    src: etc/dhclient.conf.j2
    dest: /etc/dhclient.conf
    owner: root
    group: wheel
    mode: 0644

- name: Start and enable unwind
  ansible.builtin.service:
    name: unwind
    state: started
    enabled: true
