# openbsd.vmm/handlers/main.yml

- name: reload pf
  shell: >-
    pfctl -f /etc/pf.conf
  register: pf_reloaded
  changed_when: (pf_reloaded.stdout_lines | length) > 0

- name: reload vmd
  service:
    name: "vmd"
    state: reloaded
