---
# deploy.yml

#
# all
#

- name: Deploy core services to all hosts
  hosts: testing
  roles:
    - role: openbsd.httpd
    - role: openbsd.pf
    - role: openbsd.prometheus


#
# hyperconverged
#

# - name: Deploy all services to hyperconverged host
#   hosts: hyperconverged
#   roles:
#     - role: openbsd.compute
#     - role: openbsd.mirror
#     - role: openbsd.grafana
#     - role: openbsd.nameserver
#     - role: openbsd.router
#     - role: openbsd.www
