---
# deploy.yml

- name: Deploy core services
  hosts: all
  roles:
    - role: openbsd.httpd
    - role: openbsd.pf
    - role: openbsd.prometheus
    # - role: openbsd.vmm


- name: Deploy virtualized services
  hosts: virtual
  roles:
    - role: openbsd.compute
    - role: openbsd.grafana
    - role: openbsd.iked
    - role: openbsd.ldapd
    - role: openbsd.mirror
    - role: openbsd.nameserver
    - role: openbsd.router
    - role: openbsd.www
