# SPDX-License-Identifier: ISC
#
# Copyright (c) 2023 Johnathan C. Maudlin <jcmdln@gmail.com>
---
namespace: jcmdln
name: openbsd
version: 1.1.0
description: ""

authors:
  - "Johnathan C. Maudlin <jcmdln@gmail.com>"
dependencies:
  community.crypto: ">=1.0.0"
  community.general: ">=1.0.0"
license_file: LICENSE
readme: README.md
repository: https://github.com/jcmdln/ansible-collection-openbsd
tags:
  - openbsd
  - infrastructure
  - tools
