# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
namespace: jcmdln
name: openbsd
version: 0.0.3
description: ""

authors:
  - "Johnathan C. Maudlin <jcmdln@gmail.com>"
license:
  - ISC
license_file: LICENSE.md
readme: README.md
repository: https://github.com/jcmdln/ansible-collection-openbsd
tags: []

dependencies:
  ansible.posix: "*"
  ansible.utils: "*"
  community.crypto: "*"
  community.general: "*"
