# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
collections:
  - ansible.posix
  - ansible.utils
  - community.crypto
  - community.general
roles: []
