# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Pkg
  hosts: all
  become: true

  tasks:
    - name: Update packages
      jcmdln.openbsd.pkg:
        name: "*"
        state: latest
