---
# site.yml

#
# Prepare
#

- name: Prepare hosts
  any_errors_fatal: true
  gather_facts: false
  hosts: all

  pre_tasks:
    - name: Check if Python is present
      raw: >-
        command -v python3
      changed_when: not python_exists
      register: python_exists

    - name: Install Python if missing
      raw: >-
        pkg_add python3
      when: not python_exists

    - name: Gather facts for future tasks
      setup:

  roles:
    - role: openbsd.syspatch
    - role: openbsd.sysupgrade

#
# Core
#

- name: Setup core
  any_errors_fatal: true
  gather_facts: false
  hosts: all

  roles:
    - role: openbsd.unwind

#
# DNS
#

# - name: Setup nameservers
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: dns

#   roles:
#     - openbsd.nsd

#
# Mail
#

# - name: Setup mail servers
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: mail

#   roles:
#     - role: openbsd.mail
