---
# site.yml

#
# Check
#

- name: Check hosts
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [ prepare ]

  pre_tasks:
    - name: Confirm host is running OpenBSD
      raw: >-
        uname
      changed_when: false
      failed_when: ("OpenBSD" not in uname.stdout)
      register: uname

    - name: Check if Python 3.x is present
      raw: >-
        command -v python3
      changed_when: not python
      register: python

    - name: Install Python 3.x if missing
      raw: >-
        pkg_add python3
      when: not python

#
# Facts
#

- name: Gather host facts
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [ facts ]

  tasks:
    - name: Gather facts
      setup:

#
# Update
#

- name: Update hosts
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [ never, update ]

  roles:
    - role: openbsd.syspatch
      tags: [ syspatch ]
    - role: openbsd.sysupgrade
      tags: [ sysupgrade ]

#
# Core
#

- name: Setup core
  any_errors_fatal: true
  gather_facts: false
  hosts: all
  tags: [ core ]

  roles:
    - role: openbsd.unwind
      tags: [ unwind ]

#
# DNS
#

# - name: Setup nameservers
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: dns
#   tags: [ dns ]

#   roles:
#     - openbsd.nsd

#
# Mail
#

# - name: Setup mail servers
#   any_errors_fatal: true
#   gather_facts: false
#   hosts: mail
#   tags: [ mail ]

#   roles:
#     - role: openbsd.mail
