---
# site.yml

- name: Prepare hosts
  any_errors_fatal: true
  gather_facts: false
  hosts: all

  pre_tasks:
    - name: Check if Python 3 is installed
      raw: >-
        command -v python3 || command -v python
      changed_when: false
      register: python_installed

    - name: Install Python if missing
      raw: >-
        pkg_add python3
      changed_when: false
      when: not python_installed

    - name: Gather facts
      setup:

  roles:
    - role: openbsd.syspatch
    - role: openbsd.sysupgrade
    - role: openbsd.httpd
    - role: openbsd.pf
