# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Sysupgrade
  hosts: all
  become: true

  tasks:
    - name: Upgrade to latest release or snapshot
      jcmdln.openbsd.sysupgrade:
        branch: auto
      notify: Reboot
