# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Syspatch
  hosts: all
  become: true

  tasks:
    - name: Apply all available patches
      jcmdln.openbsd.syspatch:
        apply: true
      notify: Reboot
