# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Pkg
  hosts: all

  tasks:
    - name: Update packages
      pkg:
        name: "*"
        state: latest
