---
# site.yml

#
# Prerequisites
#

- name: Prepare hosts
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Check if Python 3 is installed
      raw: command -v python3
      register: python_exists

    - name: Install Python 3 if missing
      raw: pkg_add python3
      when: not python_exists

  roles:
    - role: openbsd.syspatch
    - role: openbsd.sysupgrade

#
# Core
#

- name: Deploy core configuration(s) to all hosts
  hosts: all
  roles:
    - role: openbsd.httpd
    - role: openbsd.pf

#
# Network
#

- name: Configure network hosts
  hosts: network
  pre_tasks:
    - name: Do some vxlan shit
  roles:
    - role: openbsd.router
    - role: openbsd.switch

#
# Storage
#

- name: Prepare storage hosts
  hosts: storage
  pre_tasks:
    - name: Probably have to do stuff first
  roles:
    - role: openbsd.nfs

#
# Compute
#

- name: Prepare compute hosts to run vmm(4)
  hosts: compute
  roles:
    - role: openbsd.vmm
