# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
mail_dkim_selector: "domain"
mail_domain: "domain.tld"
mail_packages:
  - dovecot
  - dovecot-pigeonhole
  - opensmtpd-extras
  - py3-cryptography
