# SPDX-License-Identifier: ISC
#
# Copyright (c) 2024 Johnathan C. Maudlin <jcmdln@gmail.com>
---
all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

mail:
  hosts:
