# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
all:
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/libvirt/private_key"
    ansible_user: vagrant

dns:
  hosts: {}

mail:
  hosts: {}
