---
# openbsd.update/tasks/main.yml

#
# sysupgrade
#

- name: upgrade to latest release or snapshot
  sysupgrade:
    branch: 'auto'
  register: upgraded
  when: ansible_distribution_version >= '6.6'

- name: reboot host if upgraded
  reboot:
    connect_timeout: 600
    reboot_timeout: 600
  when: upgraded.changed

- name: reinstall snapshot packages if host rebooted
  command: pkg_add -ru -Dsnap
  register: packages_reinstalled
  when:
    - ansible_distribution_release == 'current'
    - upgraded.changed


#
# syspatch
#

- name: apply all available patches
  syspatch:
    apply: true
  register: patched
  when:
    - ansible_distribution_version >= '6.1'
    - ansible_distribution_release != 'current'

- name: reboot host if patched
  reboot:
    connect_timeout: 600
    reboot_timeout: 600
  when: patched.changed

- name: update packages
  package:
    name: '*'
    state: latest
  when: not packages_reinstalled.changed

- name: delete unused packages
  command: pkg_delete -a
