# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
vmm_pf_includes:
  - vmm.conf

vmm_plans:
  quark:
    disk: 5G
    memory: 256M
  electron:
    disk: 25G
    memory: 1G
  proton:
    disk: 50G
    memory: 2G
  neutron:
    disk: 50G
    memory: 4G
  atom:
    disk: 100G
    memory: 8G

customers:
  - name: jcmdln
    email: jcmdln@gmail.com
    plan: quark
    state: enable
