# openbsd.httpd/tasks/main.yml

- name: Include and set facts
  include: facts.yml

- name: create httpd(8) directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: wheel
    mode: "0755"
  with_items:
    - /etc/httpd

- name: add httpd(8) configs
  template:
    src: "etc/httpd/{{ item }}.j2"
    dest: "/etc/httpd/{{ item }}"
    owner: root
    group: wheel
    mode: "0644"
  with_items: "{{ httpd_includes }}"

- name: configure httpd(8)
  template:
    src: etc/httpd.conf.j2
    dest: /etc/httpd.conf
    owner: root
    group: wheel
    mode: "0644"
  notify:
    - reload httpd

- name: enable httpd(8) at boot
  service:
    name: "httpd"
    enabled: true

- name: start httpd(8)
  service:
    name: "httpd"
    state: started
