# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Install required packages
  jcmdln.openbsd.pkg:
    name: "{{ mail_packages }}"
    state: present

#
# SSL
#

- name: Create SSL private key for {{ mail_domain }}
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/private/{{ mail_domain }}.key"
    type: RSA

- name: Create Certificate Signing Request (CSR) for {{ mail_domain }}
  community.crypto.openssl_csr:
    path: "/etc/ssl/{{ mail_domain }}.csr"
    privatekey_path: "/etc/ssl/private/{{ mail_domain }}.key"
    common_name: "{{ mail_csr_common_name }}"
    country_name: "{{ mail_csr_country_name }}"
    email_address: "{{ mail_csr_email_address }}"
    organization_name: "{{ mail_csr_organization_name }}"

- name: Create self-signed certificate for {{ mail_domain }}
  community.crypto.x509_certificate:
    path: "/etc/ssl/{{ mail_domain }}.crt"
    privatekey_path: "/etc/ssl/private/{{ mail_domain }}.key"
    provider: selfsigned
    csr_path: "/etc/ssl/{{ mail_domain }}.csr"

#
# DKIM
#

- name: Create _dkimsign system user account
  ansible.builtin.user:
    name: _dkimsign
    state: present
    system: true
    create_home: false

- name: Create /etc/mail/dkim directory
  ansible.builtin.file:
    path: /etc/mail/dkim
    state: directory
    owner: _dkimsign
    group: _dkimsign
    mode: 0770

- name: Generate RSA2048 dkim private key
  community.crypto.openssl_privatekey:
    path: /etc/mail/dkim/{{ mail_dkim_selector }}.private.key
    size: 2048
    type: RSA
    owner: _dkimsign
    group: _dkimsign
    mode: 0600

- name: Generate RSA2048 dkim public key
  community.crypto.openssl_publickey:
    path: /etc/mail/dkim/{{ mail_dkim_selector }}.public.key
    privatekey_path: /etc/mail/dkim/{{ mail_dkim_selector }}.private.key
    owner: _dkimsign
    group: _dkimsign
    mode: 0600

#
# Dovecot
#

- name: Enable Dovecot service
  ansible.builtin.service:
    name: dovecot
    enabled: true

- name: Define Dovecot daemon login class in login.conf
  ansible.builtin.blockinfile:
    block: |
      dovecot:\
      	:openfiles-cur=1024:\
      	:openfiles-max=2048:\
      	:tc=daemon:
    marker: "# {mark} ANSIBLE MANAGED BLOCK: jcmdln.openbsd.mail"
    path: "/etc/login.conf"

- name: Configure Dovecot
  ansible.builtin.template:
    backup: true
    dest: /etc/dovecot/local.conf
    group: wheel
    mode: 0644
    owner: root
    src: etc/dovecot/local.conf.j2
  notify: Restart dovecot

- name: Comment out ssl_cert from /etc/dovecot/conf.d/10-ssl.conf
  ansible.builtin.replace:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: "^ssl_cert"
    replace: "#ssl_cert"

- name: Comment out ssl_key from /etc/dovecot/conf.d/10-ssl.conf
  ansible.builtin.replace:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: "^ssl_key"
    replace: "#ssl_key"

- name: Start Dovecot service
  ansible.builtin.service:
    name: dovecot
    state: started

#
# OpenSMTPD
#

- name: Enable smtpd
  ansible.builtin.service:
    enabled: true
    name: smtpd

- name: Configure smtpd
  ansible.builtin.template:
    backup: true
    dest: /etc/mail/smtpd.conf
    group: wheel
    mode: 0644
    owner: root
    src: etc/mail/smtpd.conf.j2
  notify: Restart smtpd

- name: Define well-known mail aliases for root@
  ansible.builtin.blockinfile:
    block: |
      # Well-known aliases
      root: {{ mail_aliases_root }}
      contact: root
      dumper: root
      info: root
      manager: root
      privacy: root

      # RFC 2142
      abuse: root
      hostmaster: root
      security: root
      webmaster: root
    marker: "# {mark} ANSIBLE MANAGED BLOCK: jcmdln.openbsd.mail"
    path: "/etc/mail/aliases"
  when:
    - mail_aliases_root is defined
    - mail_aliases_root != "root"

- name: Start smtpd
  ansible.builtin.service:
    name: smtpd
    state: started

#
# spamd
#

- name: Enable spamd
  ansible.builtin.service:
    name: spamd
    enabled: true

# FIXME: Create an rcctl module
- name: Set spamd to blacklist-only mode (ie disable greylisting)
  ansible.builtin.raw: rcctl set spamd flags -b

- name: Start spamd
  ansible.builtin.service:
    name: spamd
    state: started

- name: Enable spamlogd
  ansible.builtin.service:
    name: spamlogd
    state: started

- name: Start spamlogd
  ansible.builtin.service:
    name: spamlogd
    state: started
