---
- name: install packages
  package:
    name: '{{ prometheus_packages }}'
    state: present


- name: add httpd includes
  with_items:
    - 'prometheus.conf'
  template:
    src: 'etc/httpd/includes/{{ item }}.j2'
    dest: '/etc/httpd/includes/{{ item }}'
    owner: root
    group: wheel
    mode: '06'
  notify:
    - reload httpd

- name: update httpd_includes list
  set_fact:
    httpd_includes: "{{ httpd_includes + prometheus_httpd_includes }}"

- name: adjust httpd includes.conf
  vars:
    httpd_includes: "{{ httpd_includes | zip prometheus_httpd_includes }}"
  template:
    src: etc/httpd/includes.conf.j2
    dest: /etc/httpd/includes.conf
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - reload httpd
