---
- name: install packages
  package:
    name: "{{ prometheus_packages }}"
    state: present

#
# httpd(8)
#

- name: add httpd includes
  template:
    src: "etc/httpd/includes/{{ item }}.j2"
    dest: "/etc/httpd/includes/{{ item }}"
    owner: root
    group: wheel
    mode: "06"
  notify:
    - reload httpd
  with_items: "{{ prometheus_httpd_includes }}"

- name: update httpd_includes list
  set_fact:
    httpd_includes: "{{ httpd_includes + prometheus_httpd_includes }}"

- name: adjust httpd includes.conf
  template:
    src: etc/httpd/includes.conf.j2
    dest: /etc/httpd/includes.conf
    owner: root
    group: wheel
    mode: "0644"
  notify:
    - reload httpd
#
# pf(8)
#

# - name: add pf includes
#   template:
#     src: "etc/pf/includes/{{ item }}.j2"
#     dest: "/etc/pf/includes/{{ item }}"
#     owner: root
#     group: wheel
#     mode: "0644"
#   with_items: "{{ prometheus_pf_includes }}"

# - name: update pf_includes list
#   set_fact:
#     pf_includes: "{{ pf_includes + prometheus_pf_includes }}"

# - name: adjust /etc/pf/includes.conf
#   template:
#     src: etc/pf/includes.conf.j2
#     dest: /etc/pf/includes.conf
#     owner: root
#     group: wheel
#     mode: "0644"
#   notify:
#     - reload pf
