---
- name: create httpd(8) configuration dir(s)
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: wheel
    mode: "0755"
  with_items:
    - /etc/httpd
    - /etc/httpd/includes

- name: add httpd(8) includes
  template:
    src: "etc/httpd/includes/{{ item }}.j2"
    dest: "/etc/httpd/includes/{{ item }}"
    owner: root
    group: wheel
    mode: "0644"
  with_items: "{{ httpd_includes }}"

- name: configure httpd(8)
  template:
    src: etc/{{ item }}.j2
    dest: /etc/{{ item }}
    owner: root
    group: wheel
    mode: "0644"
  notify:
    - reload httpd
  with_items:
    - httpd.conf
    - httpd/includes.conf

- name: enable httpd(8) at boot
  service:
    name: "httpd"
    enabled: true

- name: start httpd(8)
  service:
    name: "httpd"
    state: started

- name: set httpd(8) facts
  set_fact:
    httpd_includes: "{{ httpd_includes }}"
