---
- name: create directories
  with_items:
    - /etc/httpd
    - /etc/httpd/includes
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: wheel
    mode: '0755'

- name: adjust httpd.conf
  template:
    src: etc/httpd.conf.j2
    dest: /etc/httpd.conf
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - reload httpd

- name: add httpd includes
  with_items: '{{ httpd_includes }}'
  template:
    src: 'etc/httpd/includes/{{ item }}.j2'
    dest: '/etc/httpd/includes/{{ item }}'
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - reload httpd

- name: adjust httpd includes.conf
  template:
    src: etc/httpd/includes.conf.j2
    dest: /etc/httpd/includes.conf
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - reload httpd

- name: enable httpd at boot
  service:
    name: 'httpd'
    enabled: true

- name: start httpd
  service:
    name: 'httpd'
    state: started

- name: set httpd facts
  set_fact:
    httpd_includes: '{{ httpd_includes }}'
