---
# syspatch.yml

- name: apply all available patches
  syspatch:
    apply: true
  register: syspatch

- name: reboot host if patched
  reboot:
    connect_timeout: "{{ connect_timeout }}"
    reboot_timeout: "{{ reboot_timeout }}"
  when:
    - syspatch.changed
