
- name: apply all available patches
  syspatch:
    apply: true
  register: syspatch_result
  when:
    - ansible_distribution_version is version("6.1", ">=")
    - ansible_distribution_release not in ["current", "beta"]

- name: reboot host if patched
  reboot:
    connect_timeout: "{{ connect_timeout }}"
    reboot_timeout: "{{ reboot_timeout }}"
  when:
    - syspatch_result.changed
