# SPDX-License-Identifier: ISC
#
# Copyright (c) 2024 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Pkg
  hosts: "{{ target | default('all') }}"

  any_errors_fatal: true
  gather_facts: false

  tasks:
    - name: Update packages
      jcmdln.openbsd.pkg:
        name: "*"
        state: latest
