# SPDX-License-Identifier: ISC
#
# Copyright (c) 2024 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Syspatch
  hosts: "{{ target | default('all') }}"

  any_errors_fatal: true
  gather_facts: false

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 600

  tasks:
    - name: Apply all available patches
      notify: Reboot
      jcmdln.openbsd.syspatch:
        apply: true
