# openbsd.mail/tasks/certs.yml
---
- name: Create /etc/mail/dkim directory
  ansible.builtin.file:
    path: /etc/mail/dkim
    state: directory
    owner: _dkimsign
    group: _dkimsign
    mode: 0770

- name: Generate SSL certificate
# openssl genrsa -out /etc/ssl/private/domain.tld.key 4096
# openssl req -x509 -new -nodes -sha256 -days 3650 \
#   -key /etc/ssl/private/domain.tld.key \
#   -out /etc/ssl/domain.tld.crt
# chmod 0400 /etc/ssl/private/domain.tld.key

- name: Generate DKIM
# doas -u _dkimsign openssl genrsa -out /etc/mail/dkim/domain.tld.private.key 2048
# openssl rsa -in /etc/mail/dkim/domain.tld.private.key -pubout |
#    sed '1s/.*/v=DKIM1;p=/;:nl;${s/-----.*//;q;};N;s/\n//g;b nl;'
