---
# openbsd.mail/tasks/dovecot.yml

- name: Define Dovecot daemon login class in login.conf
  ansible.builtin.blockinfile:
    block: |
      dovecot:\
              :openfiles-cur=1024:\
              :openfiles-max=2048:\
              :tc=daemon:
    marker: "# {mark} ANSIBLE MANAGED DOVECOT LOGIN CLASS"
    path: "/etc/login.conf"
