# openbsd.mail/tasks/main.yml
---
- name: Install packages if missing
  pkg:
    name: "{{ mail_packages }}"
    state: present

- include_tasks: certs.yml
- include_tasks: dovecot.yml
- include_tasks: smtpd.yml
- include_tasks: spamd.yml
