# openbsd.mail/tasks/main.yml

- name: Install packages if missing
  pkg:
    name: "{{ mail_packages }}"
    state: present

- name: Create /etc/mail directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/mail
    - /etc/mail/dkim
