# openbsd.mail/tasks/smtpd.yml
---
- name: Configure smtpd
  ansible.builtin.template:
    backup: true
    dest: /etc/mail/smtpd.conf
    src: /etc/mail/smtpd.conf.j2
    owner: root
    group: wheel
    mode: 0644
  notify:
    - Restart smtpd
