# openbsd.mail/tasks/spamd.yml
---
- name: Enable spamd
  ansible.builtin.service:
    name: spamd
    enabled: true

- name: Set spamd to blacklist-only mode (ie disable greylisting)
  ansible.builtin.raw: >-
    rcctl set spamd flags -b

- name: Start spamd
  ansible.builtin.service:
    name: spamd
    state: started
