---
# openbsd.vmm/tasks/main.yml

#
# Prerequisites
#

- name: check dmesg for nested paging support
  register: vmm_supported
  shell: >-
    dmesg | egrep "(VMX/EPT|SVM/RVI)"
  changed_when: (vmm_supported.stdout_lines | length) == 0
  notify:
    - (prereq) host missing nested paging support


#
# Quirks
#

# TODO: missing description; needs better name
- name: (quirks) increase the max length of arpq
  sysctl:
    name: 'net.inet.ip.arpq.maxlen'
    value: '1024'
    state: present


#
# httpd
#

- name: (httpd) configure httpd
  template:
    src: etc/httpd.conf
    dest: /etc/httpd.conf
    owner: root
    group: wheel
    mode: '0644'


- name: (httpd) create directories
  with_items:
    - '/var/www/htdocs/openbsd'
    - '/var/www/htdocs/openbsd/release'
  file:
    path: '{{ item }}'
    owner: root
    group: wheel
    mode: '0751'
    state: directory


- name: (httpd) enable httpd
  service:
    name: httpd
    enabled: true


- name: (httpd) start httpd
  service:
    name: httpd
    state: started


#
# vmm
#

- name: (vmm) adjust '/etc/vm.conf'
  template:
    src: etc/vm.conf.j2
    dest: /etc/vm.conf
  notify:
    - reload vmd


- name: (vmm) create directories
  with_items:
    - '/home/vm'
    - '/home/vm/default'
  file:
    path: '/home/vm'
    state: directory
    owner: root
    group: wheel


- name: (vmm) check if default vmm disk exists
  stat:
    path: '/home/vm/default/disk.qcow2'
  register: disk
  changed_when: not disk.stat.exists
  notify:
    - (vmm) create default disk


# TODO: move to vmctl module
- name: (vmm) check vmd
  shell: >
    rcctl check vmd
  changed_when: (vmd_check.stdout != 'vmd(ok)')
  notify:
    - (vmm) failed to start vmd
