---
# openbsd.vmm/tasks/main.yml

#
# Prerequisites
#

- name: check dmesg for nested paging support
  register: vmm_supported
  shell: >-
    dmesg | egrep "(VMX/EPT|SVM/RVI)"
  changed_when: (vmm_supported.stdout_lines | length) == 0

- name: (prereq) host missing nested paging support
  fail:
    msg: >
      This host does not appear to support vmm(4).  Please see
      https://www.openbsd.org/faq/faq16.html#Prerequisites for
      additional clarification.
  when: vmm_supported.changed

#
# Quirks
#

- name: (quirks) allow IP forwarding for NAT
  sysctl:
    name: "net.inet.ip.forwarding"
    value: "1"
    state: present

# TODO: missing description; needs better name
# - name: (quirks) increase the max length of arpq
#   sysctl:
#     name: "net.inet.ip.arpq.maxlen"
#     value: "1024"
#     state: present

#
# vmm
#

- name: (vmm) create directories
  with_items:
    - "/home/vm"
    - "/home/vm/default"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: wheel

- name: (vmm) configure vmm
  template:
    src: etc/vm.conf.j2
    dest: /etc/vm.conf
  notify:
    - reload vmd

- name: (vmm) check if default vmm disk exists
  stat:
    path: "/home/vm/default/quark.qcow2"
  register: disk
  changed_when: not disk.stat.exists

- name: (vmm) create default disk(s)
  shell: >-
    vmctl create -s 20G /home/vm/default/quark.qcow2
  when: disk.changed
  register: result
  changed_when: ('imagefile created' in result.stdout)
  failed_when: false

- name: (vmm) enable and start vmd service
  service:
    name: "vmd"
    state: started
    enabled: true

# TODO: move to vmctl module
- name: (vmm) check vmd
  shell: >-
    rcctl check vmd
  register: vmd_check
  changed_when: vmd_check.stdout != 'vmd(ok)'

#
# pf
#

- name: (pf) adjust '/etc/pf.conf'
  template:
    src: etc/pf.conf.j2
    dest: /etc/pf.conf
  notify:
    - reload pf
