# SPDX-License-Identifier: ISC
#
# Copyright (c) 2023 Johnathan C. Maudlin <jcmdln@gmail.com>
---
name: Release

on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: jcmdln.openbsd

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: jcmdln.openbsd

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: pip install ansible-core

      - name: Build collection
        run: ansible-galaxy collection build

      - name: Publish collection to Ansible Galaxy
        run: >
          ansible-galaxy collection publish
          --api-key ${{ secrets.GALAXY_API_KEY }}
          ${{ github.repository_owner }}-${GITHUB_REPOSITORY#*/}-${{ github.ref_name }}.tar.gz
