# SPDX-License-Identifier: AGPL-3.0-or-later
---
name: lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yml
      - .flake8
      - .yamllint
      - .prettierrc.yml
      - galaxy.yml
      - plugins/modules/*.py
      - pyproject.toml
      - requirements.yml
      - roles/**/*.j2
      - roles/**/*.md
      - roles/**/*.yml
      - site-*.yml
  push:
    paths:
      - .github/workflows/lint.yml
      - .flake8
      - .yamllint
      - .prettierrc.yml
      - galaxy.yml
      - plugins/modules/*.py
      - pyproject.toml
      - requirements.yml
      - roles/**/*.j2
      - roles/**/*.md
      - roles/**/*.yml
      - site-*.yml
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        linter: [ansible-lint, bandit, flake8, mypy]
        os: [ubuntu-22.04]
        python: ["3.8", "3.9", "3.10"]

    name: ${{ matrix.linter }}-${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: |
            requirements/bandit.txt
            requirements/flake8.txt
            requirements/mypy.txt
            requirements/tox.txt

      - name: Setup venv cache
        uses: actions/cache@v3
        id: cache-venv
        with:
          key: venv-${{ matrix.linter }}-${{ matrix.python }}-${{ matrix.os }}-${{ hashFiles('requirements/*.txt') }}
          path: .venv

      - name: Install Tox
        run: pip install -r requirements/tox.txt

      - name: Setup Tox cache
        uses: actions/cache@v3
        id: cache-tox
        with:
          key: tox-${{ matrix.linter }}-${{ matrix.python }}-${{ matrix.os }}-${{ hashFiles('requirements/*.txt') }}
          path: .tox/${{ matrix.linter }}

      - name: Run ${{ matrix.linter }}
        run: tox -e ${{ matrix.linter }}
