# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C. Maudlin <jcmdln@gmail.com>
---
name: lint

on:
  pull_request:
    paths:
      - .ansible-lint
      - .flake8
      - .github/workflows/lint.yml
      - .prettierrc.yml
      - .yamllint
      - ansible.cfg
      - galaxy.yml
      - poetry.lock
      - poetry.toml
      - pyproject.toml
      - roles/**/*.yml
      - site-*.yml
  push:
    paths:
      - .ansible-lint
      - .flake8
      - .github/workflows/lint.yml
      - .prettierrc.yml
      - .yamllint
      - ansible.cfg
      - galaxy.yml
      - poetry.lock
      - poetry.toml
      - pyproject.toml
      - roles/**/*.yml
      - site-*.yml
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.9", "3.10", "3.11"]

    name: python${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            poetry.lock

      - name: Setup venv cache
        uses: actions/cache@v3
        id: venv
        with:
          key: venv-${{ hashFiles('pyproject.toml', 'poetry.lock') }}
          path: .venv/

      - name: Setup Tox cache
        uses: actions/cache@v3
        id: tox
        with:
          key: tox-${{ hashFiles('pyproject.toml', 'poetry.lock') }}
          path: .tox/

      - name: Install Poetry
        run: pip install poetry

      - name: Install Tox
        run: poetry install --only tox

      - name: Run tox
        run: poetry run tox
